# Docker Install
---
- hosts: all
  become: true
  tasks:
    - name: Requirement
      tags:
           - docker-install
      apt:
        name: "{{ item }}"
        state: latest 
      with_items:
            -  apt-transport-https
            -  ca-certificates
            -  curl
            -  gnupg
            -  lsb-release
            -  python3-pip

    - name: Add Docker’s official GPG key
      tags:
           - docker-install
      apt_key:
        url:   https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Add Docker Repository
      apt_repository:
        repo:  deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt:
        name: "{{ item }}"
        update_cache: true
        state: latest 
      with_items:
            -  docker-ce
            -  docker-ce-cli
            -  containerd.io
    - name: Install Docker Module for Python
      pip:
        name: docker